sudo: required
services:
  - docker
language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: bash -xe ./travis/static-analysis.sh && bash -xe ./travis/unit-tests.sh && bash -xe ./travis/test-deploy.sh
