cartrabbit:
  image: rabbitmq
  container_name: cartrabbit

cartmysql:
  image: mysql
  container_name: cartmysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: pacifica_cart
    MYSQL_USER: cartd
    MYSQL_PASSWORD: cartd

archiveinterface:
  image: pacifica/archiveinterface
  container_name: archiveinterface
  ports:
    - 8080:8080
  volumes:
    - /srv:/srv


cartworkers:
  container_name: cartworkers
  build: .
  dockerfile: Dockerfile
  links:
    - cartrabbit:amqp
    - cartmysql:mysql
    - archiveinterface:archivei
  volumes:
    - /shared:/shared
  environment:
    VOLUME_PATH: /shared/
    ARCHIVE_INTERFACE_URL: None

cartserver:
  container_name: cartserver
  build: .
  dockerfile: Dockerfile.wsgi
  ports:
    - 8081:8081
  links:
    - cartrabbit:amqp
    - cartmysql:mysql
    - archiveinterface:archivei
  volumes:
    - /shared:/shared
  environment:
    VOLUME_PATH: /shared/
    ARCHIVE_INTERFACE_URL: None