cartrabbit:
  image: rabbitmq
cartmysql:
  image: mysql
  environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: pacifica_cart
     MYSQL_USER: cartd
     MYSQL_PASSWORD: cartd
cartworkers:
  build: .
  dockerfile: Dockerfile
  links:
    - cartrabbit:amqp
    - cartmysql:mysql
cartserver:
  build: .
  dockerfile: Dockerfile.wsgi
  ports:
    - 8080:8080
  links:
    - cartrabbit:amqp
    - cartmysql:mysql

